# Generated by Django 5.2.8 on 2025-11-26 02:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_client_id', models.CharField(max_length=255)),
                ('ml_client_secret', models.CharField(max_length=255)),
                ('ml_access_token', models.TextField(blank=True, null=True)),
                ('ml_refresh_token', models.TextField(blank=True, null=True)),
                ('ml_token_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('shopee_partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shopee_partner_key', models.CharField(blank=True, max_length=255, null=True)),
                ('shopee_access_token', models.TextField(blank=True, null=True)),
                ('shopee_refresh_token', models.TextField(blank=True, null=True)),
                ('shopee_shop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_profile', to='finance_core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('LUCRO_REAL', 'Lucro Real'), ('LUCRO_PRESUMIDO', 'Lucro Presumido'), ('SIMPLES', 'Simples Nacional')], default='LUCRO_REAL', max_length=20)),
                ('icms_benefit_flag', models.BooleanField(default=False, help_text='Ativar se houver benefício fiscal de ICMS (ex: TTS)')),
                ('effective_tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota efetiva de ICMS na saída caso tenha benefício fiscal.', max_digits=5)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='finance_core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsCostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ML', 'Mercado Livre'), ('SHOPEE', 'Shopee')], max_length=20)),
                ('shipping_method', models.CharField(max_length=50)),
                ('fixed_cost_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_costs', to='finance_core.organization')),
            ],
            options={
                'unique_together': {('organization', 'platform', 'shipping_method')},
            },
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('ncm', models.CharField(max_length=20)),
                ('gross_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_pis', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_cofins', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_costs', to='finance_core.organization')),
            ],
            options={
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('ML', 'Mercado Livre'), ('SHOPEE', 'Shopee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_shipping_method', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_cost_platform', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calculated_fixed_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_fixed_cost_applied', models.BooleanField(default=False, help_text='Se True, ignora o custo da plataforma e usa apenas o fixo.')),
                ('net_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='finance_core.organization')),
            ],
            options={
                'unique_together': {('organization', 'external_id', 'platform')},
            },
        ),
    ]
